# main.py 這個是第一次滙入到DATABASE 的資料。次後不需要再用
from sqlmodel import SQLModel, create_engine, Session
from ikea_models import Mattress, BedFrame, Chair

# 建立 SQLite 資料庫
sqlite_file_name = "ikea.db"
engine = create_engine(f"sqlite:///{sqlite_file_name}", echo=True)

# 建立資料表（如果尚未建立）
SQLModel.metadata.create_all(engine)

# 產品資料
mattress_list = [
    Mattress(
        product_id="903.195.12", 
        name="HAUGSVÄR", 
        category="床褥", 
        price=348.59,
        package_dimension="150, 80, 24", 
        length=200, 
        width=150, 
        height=20,
        weight=24.8, 
        stock=17, 
        material="spring", 
        warranty=12, 
        firmness="firm", 
        feature="彈簧床褥"),
    
    Mattress(
        product_id="903.829.49", 
        name="HYLLESTAD", 
        category="床褥", 
        price=576.1,
        package_dimension="148, 80, 21", 
        length=200, 
        width=90, 
        height=19,
        weight=29.9, 
        stock=9, 
        material="spring", 
        warranty=8, 
        firmness="medium", 
        feature="彈簧床褥"),
    
     Mattress(
        product_id="903.882.62",
        name="HOVAG",
        category="床褥",
        price=356.88,
        package_dimension="142, 80, 21",
        weight=29.0,
        stock=1,
        width=150,
        length=200,
        height=22,
        material="foam",
        warranty=12,
        firmness="medium",
        feature="彈簧床褥"),

    Mattress(
        product_id="903.814.95",
        name="MORGEDAL",
        category="床褥",
        price=561.37,
        package_dimension="145, 80, 23",
        weight=25.4,
        stock=7,
        width=90,
        length=200,
        height=21,
        material="foam",
        warranty=9,
        firmness="firm",
        feature="彈簧床褥"),

    Mattress(
        product_id="903.353.15",
        name="MALFORS",
        category="床褥",
        price=485.04,
        package_dimension="152, 80, 23",
        weight=24.6,
        stock=2,
        width=150,
        length=200,
        height=23,
        material="spring",
        warranty=5,
        firmness="medium firm",
        feature="彈簧床褥"),

Mattress(
        product_id="903.941.38",
        name="MATRAND",
        category="床褥",
        price=453.77,
        package_dimension="157, 80, 21",
        weight=29.2,
        stock=0,
        width=135,
        length=200,
        height=20,
        material="latex",
        warranty=12,
        firmness="soft",
        feature="彈簧床褥"),

Mattress(
        product_id="903.673.76",
        name="MYRBACKA",
        category="床褥",
        price=366.13,
        package_dimension="149, 80, 23",
        weight=28.2,
        stock=10,
        width=150,
        length=200,
        height=23,
        material="latex",
        warranty=6,
        firmness="medium",
        feature="彈簧床褥"),

Mattress(
        product_id="903.858.83",
        name="MINNESUND",
        category="床褥",
        price=1563.7,
        package_dimension="147, 80, 18",
        weight=25.9,
        stock=3,
        width=135,
        length=200,
        height=20,
        material="spring",
        warranty=14,
        firmness="firm",
        feature="彈簧床褥"),

Mattress(
        product_id="903.432.69",
        name="MEISTERVIK",
        category="床褥",
        price=341.02,
        package_dimension="144, 80, 21",
        weight=22.2,
        stock=20,
        width=90,
        length=200,
        height=18,
        material="foam",
        warranty=11,
        firmness="medium",
        feature="彈簧床褥"  ),

Mattress(
        product_id="903.961.68",
        name="VESTERÖY",
        category="床褥",
        price=389.47,
        package_dimension="145, 80, 21",
        weight=29.5,
        stock=8,
        width=90,
        length=200,
        height=22,
        material="foam",
        warranty=14,
        firmness="soft",
        feature="彈簧床褥"),]

bedframe_list = [
        BedFrame(
        product_id="BF100", 
        name="床架系列 A", 
        category="床架", 
        price=2519.44,
        package_dimension="149.8, 36.8, 12.5", 
        length=150, 
        width=40, 
        height=13,  # 長寬高如不適用，設為0或適當值
        weight=31.9, 
        stock=19, 
        style="雙人床架 - (適用135x189cm床褥)", 
        color="黑色",
        material="膠合板", 
        assembly_time=32), 
    
BedFrame(
        product_id="BF101",
        name="床架系列 B",
        category="床架",
        price=2229.75,
        package_dimension="156.0, 38.8, 18.1",
        length=157, 
        width=40, 
        height=18,  # 長寬高如不適用，設為0或適當值
        weight=43.5,
        stock=10,
        style="雙人床架 - (適用135x189cm床褥)",
        color="淺木色",
        material="鋼架",
        assembly_time=78
),

BedFrame(
        product_id="BF102",
        name="床架系列 C",
        category="床架",
        price=1536.96,
        package_dimension="140.9, 36.9, 23.7",
        length=145, 
        width=44, 
        height=23,  # 長寬高如不適用，設為0或適當值
        weight=41.8,
        stock=7,
        style="雙人床架 - (適用135x189cm床褥)",
        color="深灰色",
        material="MDF纖維板",
        assembly_time=89
),

BedFrame(
    product_id="BF103",
    name="床架系列 D",
    category="床架",
    price=2285.3,
    package_dimension="147.3, 36.5, 23.3",
    weight=39.6,
    stock=3,
    style="特大雙人床架 - (適用150x200cm床褥)",
    color="黑色",
    material="MDF纖維板",
    assembly_time=36),

BedFrame(
    product_id="BF104",
    name="床架系列 E",
    category="床架",
    price=1885.52,
    package_dimension="140.7, 37.7, 12.5",
    weight=58.6,
    stock=17,
    style="碌架床 - (適用92x189cm床褥,1或2張床褥)",
    color="白色",
    material="膠合板",
    assembly_time=66
),

BedFrame(
    product_id="BF105",
    name="床架系列 F",
    category="床架",
    price=2760.42,
    package_dimension="148.9, 41.4, 22.7",
    weight=30.9,
    stock=9,
    style="雙人床架 - (適用135x189cm床褥)",
    color="白色",
    material="鋼架",
    assembly_time=62
),

BedFrame(
    product_id="BF106",
    name="床架系列 G",
    category="床架",
    price=2780.65,
    package_dimension="153.4, 32.1, 14.4",
    weight=55.0,
    stock=10,
    style="雙人床架 - (適用135x189cm床褥)",
    color="淺木色",
    material="鋼架",
    assembly_time=31),

BedFrame(
    product_id="BF107",
    name="床架系列 H",
    category="床架",
    price=2743.87,
    package_dimension="142.6, 37.1, 12.0",
    weight=59.8,
    stock=5,
    style="特別訂製雙人床 - (適用151cm或以上特別訂製床褥)",
    color="淺木色",
    material="金屬+木板",
    assembly_time=42),

BedFrame(
    product_id="BF108",
    name="床架系列 I",
    category="床架",
    price=1303.32,
    package_dimension="157.0, 38.7, 24.9",
    weight=41.1,
    stock=0,
    style="雙人床架 - (適用135x189cm床褥)",
    color="白色",
    material="實木",
    assembly_time=84),

BedFrame(
    product_id="BF109",
    name="床架系列 J",
    category="床架",
    price=2579.33,
    package_dimension="143.9, 33.4, 14.7",
    weight=39.1,
    stock=8,
    style="單人床架 - (適用92x189cm床褥)",
    color="深灰色",
    material="膠合板",
    assembly_time=72),]

chair_list = [
    Chair(
        product_id="CH100", 
        name="椅子系列 A", 
        category="椅子", 
        price=1479.29,
        package_dimension="64.9, 48.1, 21.5", 
        length=0, 
        width=0, 
        height=0,
        weight=9.6, 
        stock=8, 
        chair_type="餐椅", 
        backrest_height="高椅背", 
        armrest="連扶手",
        surface_type="真皮", 
        material="塑膠", 
        has_wheels=False, 
        need_assembly=True,
        color="白色", 
        has_headrest=False, 
        adjustable_height=False),

    Chair(
        product_id="CH101",
        name="椅子系列 B",
        category="椅子",
        price=588.56,
        package_dimension="88.4, 48.9, 24.8",
        weight=16.6,
        stock=19,
        chair_type="電腦椅",
        backrest_height="高椅背",
        armrest="連扶手",
        surface_type="無外皮",
        material="金屬",
        has_wheels=False,
        need_assembly=True,
        color="藍色",
        has_headrest=False,
        adjustable_height=True),

Chair(
    product_id="CH102",
    name="椅子系列 C",
    category="椅子",
    price=375.36,
    package_dimension="74.7, 52.6, 18.1",
    weight=10.4,
    stock=10,
    chair_type="辦公椅",
    backrest_height="低椅背",
    armrest="不連扶手",
    surface_type="仿皮",
    material="鋁合金",
    has_wheels=False,
    need_assembly=True,
    color="灰色",
    has_headrest=False,
    adjustable_height=False
),

Chair(
    product_id="CH103",
    name="椅子系列 D",
    category="椅子",
    price=1085.37,
    package_dimension="89.5, 46.7, 17.3",
    weight=12.1,
    stock=15,
    chair_type="辦公椅",
    backrest_height="高椅背",
    armrest="連扶手",
    surface_type="仿皮",
    material="鋼+網布",
    has_wheels=True,
    need_assembly=False,
    color="灰色",
    has_headrest=False,
    adjustable_height=True
),

Chair(
    product_id="CH104",
    name="椅子系列 E",
    category="椅子",
    price=487.93,
    package_dimension="63.0, 46.4, 13.5",
    weight=17.2,
    stock=12,
    chair_type="電腦椅",
    backrest_height="低椅背",
    armrest="連扶手",
    surface_type="真皮",
    material="塑膠",
    has_wheels=False,
    need_assembly=True,
    color="黑色",
    has_headrest=False,
    adjustable_height=False),

Chair(
        product_id="CH105",
        name="椅子系列 F",
        category="椅子",
        price=604.35,
        package_dimension="69.7, 58.0, 19.4",
        weight=14.9,
        stock=16,
        chair_type="電競椅",
        backrest_height="低椅背",
        armrest="不連扶手",
        surface_type="無外皮",
        material="鋼+網布",
        has_wheels=True,
        need_assembly=True,
        color="紅色",
        has_headrest=False,
        adjustable_height=False),

Chair(
    product_id="CH106",
    name="椅子系列 G",
    category="椅子",
    price=404.75,
    package_dimension="63.2, 46.6, 22.3",
    weight=13.5,
    stock=7,
    chair_type="餐椅",
    backrest_height="低椅背",
    armrest="連扶手",
    surface_type="真皮",
    material="鋼+網布",
    has_wheels=False,
    need_assembly=False,
    color="黑色",
    has_headrest=False,
    adjustable_height=True
),

Chair(
    product_id="CH107",
    name="椅子系列 H",
    category="椅子",
    price=425.42,
    package_dimension="61.1, 52.0, 20.2",
    weight=8.4,
    stock=13,
    chair_type="電腦椅",
    backrest_height="高椅背",
    armrest="不連扶手",
    surface_type="仿皮",
    material="實木",
    has_wheels=True,
    need_assembly=False,
    color="灰色",
    has_headrest=False,
    adjustable_height=True
),

Chair(
    product_id="CH108",
    name="椅子系列 I",
    category="椅子",
    price=967.39,
    package_dimension="67.0, 54.4, 24.2",
    weight=7.6,
    stock=5,
    chair_type="電競椅",
    backrest_height="低椅背",
    armrest="連扶手",
    surface_type="仿皮",
    material="塑膠",
    has_wheels=False,
    need_assembly=False,
    color="灰色",
    has_headrest=True,
    adjustable_height=False
),

Chair(
    product_id="CH109",
    name="椅子系列 J",
    category="椅子",
    price=1082.12,
    package_dimension="81.1, 56.8, 10.8",
    weight=12.7,
    stock=17,
    chair_type="電腦椅",
    backrest_height="高椅背",
    armrest="不連扶手",
    surface_type="真皮",
    material="鋼+網布",
    has_wheels=True,
    need_assembly=False,
    color="藍色",
    has_headrest=False,
    adjustable_height=False
), ]

# ⏬ 批量匯入資料庫
with Session(engine) as session:
    session.add_all(mattress_list + bedframe_list + chair_list)
    session.commit()

print(f"✅ 成功寫入 {len(mattress_list)} 張床褥, {len(bedframe_list)} 張床架, {len(chair_list)} 張椅子到資料庫！")
